/**
 * Copyright (c) 2026 FutureMindsDev. All rights reserved.
 *
 * LazyDev™ is a trademark of FutureMindsDev.
 * Organization : https://github.com/FutureMindsDev
 *
 * Authors:
 *   Arkar Chan Myae  <https://github.com/arkar-chanmyae>
 *   Khin Me Me Latt  <https://github.com/KhinMeMeLatt>
 *
 * Licensed under the MIT License.
 * See LICENSE file in the project root for full license information.
 */

/* eslint-disable */
import { BaseMessage } from '@langchain/core/messages';
import { StateGraphArgs } from '@langchain/langgraph';

// The state channels structure for our multi-agent graph
export interface AgentState {
  // Ordered conversation history and system messages
  messages: BaseMessage[];

  // The raw issue payload from GitHub
  issuePayload: any;

  // Triage output (issue type, search terms, likely files) — formerly
  // produced by IssueAnalyzerAgent and consumed by ResearchAgent. Both
  // agents are now merged into PlannerAgent, which derives search terms
  // itself. Kept in the state shape for backward compatibility but no
  // longer read or written by any active agent.
  triageContext?: any;

  // Intermediate research context gathered by the research agent
  researchContext?: string;

  // The generated plan from the planning agent
  implementationPlan?: string;

  // The patch generated by the patch agent
  generatedPatch?: string;

  // Human-readable list of intended changes that failed to apply (e.g. the
  // LLM guessed a file path that doesn't exist). Empty string means the last
  // patch-generation attempt applied everything cleanly. Surfaced by GitAgent
  // in the PR body so a reviewer isn't misled into thinking the fix is complete.
  unappliedChanges?: string;

  // Branch the fix/feature was pushed to, and the resulting PR's HTML URL.
  // Set by GitAgent on success so AuditLogService.logPipelineOutcome can
  // persist them for the dashboard Run Detail screen. Both are undefined on
  // validation failure (git node never runs) or when push/PR creation fails.
  branch?: string;
  prUrl?: string;

  // Feedback from validation (compile errors, test failures)
  validationFeedback?: string;

  // Flag indicating if validation passed
  isValid?: boolean;

  // Counter to prevent infinite validation loops
  validationAttempts?: number;

  // Dedicated message history for the PatchGeneratorAgent's tool loop
  // (read_file / get_symbols_overview / find_symbol / replace_symbol_body /
  // etc.), kept separate from the main `messages` timeline so the generator
  // — which may run on a different (cheaper) model than the planner — never
  // has to pay for or parse the research/planning conversation's tool-call
  // history. Explicitly reset to [] by the `planner` and `human_feedback`
  // nodes so every new patch-generation attempt starts fresh; the patcher
  // and patcher_tools nodes then grow it across their own inner loop.
  patchMessages?: any[];

  // Dedicated message history for the PlannerAgent's tool loop
  // (search_codebase / read_code_file / get_file_symbols / list_dir /
  // read_serena_memory / find_symbol), kept separate from the main
  // `messages` timeline for the same reasons as patchMessages. The planner
  // and planner_tools nodes grow it across their inner loop; it is
  // implicitly empty at the start of a pipeline run (default: () => []).
  plannerMessages?: any[];
}

// Defining how state is updated across nodes (Channels)
export const agentStateChannels: StateGraphArgs<AgentState>['channels'] = {
  messages: {
    // Append new messages to the existing array
    reducer: (a: BaseMessage[], b: BaseMessage[]) => a.concat(b),
    default: () => [],
  },
  issuePayload: {
    reducer: (a: any, b: any) => (b ? b : a),
    default: () => null,
  },
  triageContext: {
    reducer: (a: any, b: any) => (b !== undefined ? b : a),
    default: () => undefined,
  },
  researchContext: {
    reducer: (a: string | undefined, b: string | undefined) =>
      b !== undefined ? b : a,
    default: () => undefined,
  },
  implementationPlan: {
    reducer: (a: string | undefined, b: string | undefined) =>
      b !== undefined ? b : a,
    default: () => undefined,
  },
  generatedPatch: {
    reducer: (a: string | undefined, b: string | undefined) =>
      b !== undefined ? b : a,
    default: () => undefined,
  },
  unappliedChanges: {
    reducer: (a: string | undefined, b: string | undefined) =>
      b !== undefined ? b : a,
    default: () => undefined,
  },
  branch: {
    reducer: (a: string | undefined, b: string | undefined) =>
      b !== undefined ? b : a,
    default: () => undefined,
  },
  prUrl: {
    reducer: (a: string | undefined, b: string | undefined) =>
      b !== undefined ? b : a,
    default: () => undefined,
  },
  validationFeedback: {
    reducer: (a: string | undefined, b: string | undefined) =>
      b !== undefined ? b : a,
    default: () => undefined,
  },
  isValid: {
    reducer: (a: boolean | undefined, b: boolean | undefined) =>
      b !== undefined ? b : a,
    default: () => undefined,
  },
  validationAttempts: {
    reducer: (a: number | undefined, b: number | undefined) =>
      b !== undefined ? b : a,
    default: () => 0,
  },
  // Replace (not concat) semantics: the patcher/patcher_tools nodes read the
  // current array, compute the full new array themselves, and return it
  // whole — mirroring how ToolNode.invoke() is used against a bare message
  // array. This lets `planner`/`human_feedback` reset the channel to []
  // simply by returning `patchMessages: []`.
  patchMessages: {
    reducer: (a: any[] | undefined, b: any[] | undefined) =>
      b !== undefined ? b : a,
    default: () => [],
  },
  // Same replace semantics as patchMessages, for the planner's own tool
  // loop (planner ⇄ planner_tools).
  plannerMessages: {
    reducer: (a: any[] | undefined, b: any[] | undefined) =>
      b !== undefined ? b : a,
    default: () => [],
  },
};
