/**
 * Copyright (c) 2026 FutureMindsDev. All rights reserved.
 *
 * LazyDev™ is a trademark of FutureMindsDev.
 * Organization : https://github.com/FutureMindsDev
 *
 * Authors:
 *   Arkar Chan Myae  <https://github.com/arkar-chanmyae>
 *   Khin Me Me Latt  <https://github.com/KhinMeMeLatt>
 *
 * Licensed under the MIT License.
 * See LICENSE file in the project root for full license information.
 */

/* eslint-disable */
import { Injectable, Logger } from '@nestjs/common';
import { AgentState } from '../graph.state';
import { GitService } from '../../git/git.service';
import { SystemMessage } from '@langchain/core/messages';
import * as fs from 'fs/promises';
import * as path from 'path';

import { GithubService } from '../../github/github.service';
import { SerenaMcpService } from '../../intelligence/serena-mcp.service';
import { commitTypeFor, type WorkKind } from '../../common/work-kind';
import { extractMcpText } from '../../common/mcp-text';
import { formatLessonsEntries } from '../../common/lessons-learned-formatter';

/** Where LazyDev's committed memory snapshot lives inside the target repo. */
const MEMORY_DIR = path.join('.lazydev', 'memory');
const MEMORY_HEADER =
  '<!-- Auto-generated by LazyDev. Do not edit by hand — regenerated on future runs. -->\n\n';

@Injectable()
export class GitAgent {
  private readonly logger = new Logger(GitAgent.name);

  constructor(
    private readonly gitService: GitService,
    private readonly githubService: GithubService,
    private readonly serenaMcp: SerenaMcpService,
  ) {}

  async invoke(state: AgentState): Promise<Partial<AgentState>> {
    this.logger.log('Preparing to commit and push changes...');

    if (!state.isValid) {
      this.logger.warn('Cannot push invalid patch.');
      return {
        messages: [
          new SystemMessage('Git push aborted due to validation failure.'),
        ],
      };
    }

    // Use the isolated worktree — this is where PatchGeneratorAgent wrote the
    // patched files. Using repo-cache/repo here would commit the unpatched shared
    // clone instead.
    const worktreePath = state.issuePayload?.worktreePath;
    if (!worktreePath) {
      this.logger.error('No worktreePath in state — cannot commit changes.');
      return { messages: [new SystemMessage('Git push aborted: no worktree path.')] };
    }

    const issueNumber = state.issuePayload?.issue?.number || Date.now();
    const issueTitle = state.issuePayload?.issue?.title || 'ai-generated-fix';

    // Webhook-driven runs are fixes; `feature` comes from the MCP
    // implement_new_feature tool and must not be labelled as a fix.
    const kind: WorkKind = state.issuePayload?.kind === 'feature' ? 'feature' : 'fix';
    const isFeature = kind === 'feature';

    const fixBranchName = this.gitService.buildBranchName(
      issueNumber,
      issueTitle,
      kind,
    );
    const commitMessage = `${commitTypeFor(kind)}: ${
      isFeature ? 'implement' : 'resolve'
    } issue #${issueNumber}\n\nGenerated autonomously by LazyDev.`;

    // Refresh the repo's own copy of LazyDev's memories before committing, so
    // they ride along with the fix/feature itself: versioned in git history,
    // visible to human collaborators, and durable even if the server-side
    // repo-cache clone that Serena's memories actually live in is ever wiped.
    await this.syncMemoriesIntoWorktree(worktreePath, state.issuePayload?.repoPath);

    try {
      this.logger.log(`Creating fix branch ${fixBranchName} in worktree and pushing...`);
      await this.gitService.createFixBranch(worktreePath, fixBranchName);
      await this.gitService.commitAndPush(worktreePath, commitMessage, fixBranchName);
      
      let prMessage = '';
      let prUrl: string | undefined;
      try {
        const installationId = state.issuePayload?.installation?.id;
        const owner = state.issuePayload?.repository?.owner?.login;
        const repo = state.issuePayload?.repository?.name;
        const defaultBranch = state.issuePayload?.repository?.default_branch || 'main';

        if (installationId && owner && repo) {
          this.logger.log(`Creating Pull Request to merge ${fixBranchName} into ${defaultBranch}...`);

          const planDescription = state.implementationPlan
            ? `\n\n### ${isFeature ? 'Implementation Plan' : 'Fix Approach'}\n\n${state.implementationPlan}`
            : '';

          // Some intended changes may not have made it in (e.g. the LLM
          // targeted a file that turned out not to exist). Say so up front so
          // a reviewer doesn't assume the diff fully resolves the issue.
          const unappliedNote = state.unappliedChanges
            ? `\n\n### ⚠️ Note: Some intended changes could not be applied\n\n${state.unappliedChanges}`
            : '';

          // Feature issue titles already read "Feature: ...", so prefixing
          // "Fix:" would produce "Fix: Feature: ...".
          const prTitle = isFeature ? issueTitle : `Fix: ${issueTitle}`;

          const octokit = await this.githubService.getInstallationOctokit(installationId);
          const pr = await octokit.rest.pulls.create({
            owner,
            repo,
            title: prTitle,
            head: fixBranchName,
            base: defaultBranch,
            body: `Resolves #${issueNumber}\n\nGenerated autonomously by LazyDev.${planDescription}${unappliedNote}`,
          });
          prUrl = pr.data.html_url;
          prMessage = `\nPull Request created: ${prUrl}`;
          this.logger.log(prMessage);
        } else {
          this.logger.warn('Missing GitHub metadata to create a Pull Request automatically.');
        }
      } catch (prError: any) {
        const errorMessage: string = prError.message || '';

        // GitHub returns 422 Validation Failed when a PR already exists for this branch.
        // In that case, find and return the existing PR URL instead of failing.
        if (errorMessage.includes('pull request already exists') || errorMessage.includes('A pull request already exists')) {
          try {
            const octokit2 = await this.githubService.getInstallationOctokit(state.issuePayload?.installation?.id);
            const existingPrs = await octokit2.rest.pulls.list({
              owner: state.issuePayload?.repository?.owner?.login,
              repo: state.issuePayload?.repository?.name,
              head: `${state.issuePayload?.repository?.owner?.login}:${fixBranchName}`,
              state: 'open',
            });
            if (existingPrs.data.length > 0) {
              prUrl = existingPrs.data[0].html_url;
              prMessage = `\nPull Request (already open): ${prUrl}`;
              this.logger.log(`Existing PR found: ${prUrl}`);
            }
          } catch {
            prMessage = `\n(Note: PR already exists but could not fetch its URL.)`;
          }
        } else {
          this.logger.error(`Failed to create Pull Request: ${errorMessage}`);
          prMessage = `\n(Note: Branch pushed, but PR creation failed: ${errorMessage})`;
        }
      }

      return {
        // Persist branch + prUrl so AuditLogService.logPipelineOutcome can
        // store them for the dashboard Run Detail screen.
        branch: fixBranchName,
        prUrl,
        messages: [new SystemMessage(`Successfully pushed branch ${fixBranchName}.${prMessage}`)]
      };
    } catch (e: any) {
      this.logger.error(`Git push failed: ${e.message}`);
      return {
        messages: [new SystemMessage(`Git push failed: ${e.message}`)]
      };
    }
  }

  /**
   * Writes LazyDev's current Serena memories into `.lazydev/memory/` inside
   * the worktree, as plain tracked files. They ride along with the same
   * `git add .` that `GitService.commitAndPush` runs next, so they end up
   * versioned in the repo's own history — visible to human collaborators and
   * durable even if the server-side repo-cache clone (where these memories
   * actually live, per `OnboardingAgent`/`ValidationAgent`) is ever wiped.
   *
   * Best-effort: failures here must never block the actual fix from being
   * committed and pushed.
   */
  private async syncMemoriesIntoWorktree(
    worktreePath: string,
    repoPath?: string,
  ): Promise<void> {
    if (!repoPath) {
      this.logger.warn(
        'No repoPath in state — skipping memory sync into the repo.',
      );
      return;
    }

    try {
      await this.serenaMcp.activateProject(repoPath);

      const memoryDir = path.join(worktreePath, MEMORY_DIR);
      await fs.mkdir(memoryDir, { recursive: true });

      const structureResult = await this.serenaMcp.readMemory('global_repo_structure');
      const structureText = extractMcpText(structureResult);
      if (structureText) {
        await fs.writeFile(
          path.join(memoryDir, 'global_repo_structure.md'),
          `${MEMORY_HEADER}${structureText}\n`,
          'utf8',
        );
      }

      if (process.env.ENABLE_SERENA_ISSUE_HISTORY === 'true') {
        const lessonsResult = await this.serenaMcp.readMemory('historical_issues_and_lessons');
        // Uncapped: this is the durable, human-facing copy — unlike
        // PlannerAgent's prompt-context copy, it doesn't need to stay small.
        const lessonsText = formatLessonsEntries(lessonsResult);
        if (lessonsText) {
          await fs.writeFile(
            path.join(memoryDir, 'historical_issues_and_lessons.md'),
            `${MEMORY_HEADER}${lessonsText}\n`,
            'utf8',
          );
        }
      }

      // Reactivate the worktree so anything else in this job that assumes it
      // is the active Serena project (there isn't anything else in GitAgent
      // today, but every other agent follows this convention) still does.
      await this.serenaMcp.activateProject(worktreePath);
    } catch (e: any) {
      this.logger.warn(`Could not sync Serena memories into the repo: ${e.message}`);
    }
  }
}
